const pages=[...document.querySelectorAll('.page')],dots=[...document.querySelectorAll('.p')];let current=0;
function go(i){pages[current].classList.remove('active');current=i;pages[current].classList.add('active');dots.forEach((d,n)=>d.classList.toggle('active',n===current))}
const gift=document.getElementById('gift');document.getElementById('openGift').onclick=()=>{gift.classList.add('open');setTimeout(()=>go(1),650)};
document.querySelectorAll('.next').forEach(b=>b.onclick=()=>go(pages.indexOf(document.getElementById(b.dataset.next))));
let popped=0;const reason=document.getElementById('reasonBox');document.querySelectorAll('.balloon').forEach(b=>b.onclick=()=>{if(b.classList.contains('popped'))return;b.classList.add('popped');popped++;reason.textContent=b.dataset.msg;if(popped===5){setTimeout(()=>{reason.textContent="You found all five. But honestly... I could name a hundred. ❤️";document.getElementById('balloonNext').classList.add('visible')},500)}});
const envelope=document.getElementById('envelope');envelope.onclick=()=>{envelope.classList.add('open');setTimeout(()=>{document.getElementById('finalLetter').classList.add('show');document.querySelector('.tap-letter').style.display='none';document.querySelector('.replay').classList.add('show')},750)};
document.getElementById('replay').onclick=()=>{document.getElementById('finalLetter').classList.remove('show');envelope.classList.remove('open');document.querySelector('.tap-letter').style.display='block';document.querySelector('.replay').classList.remove('show');document.querySelectorAll('.balloon').forEach(b=>b.classList.remove('popped'));popped=0;reason.textContent="Pop all five to unlock the next chapter ❤️";document.getElementById('balloonNext').classList.remove('visible');gift.classList.remove('open');go(0)};
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&current<pages.length-1)go(current+1);if(e.key==='ArrowLeft'&&current>0)go(current-1)});
let sx=0;document.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});document.addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>70){if(dx<0&&current<pages.length-1)go(current+1);if(dx>0&&current>0)go(current-1)}},{passive:true});
const p=document.getElementById('particles');for(let i=0;i<40;i++){let x=document.createElement('span');x.className='particle';x.style.left=Math.random()*100+'%';x.style.animationDelay=(-Math.random()*7)+'s';x.style.animationDuration=(5+Math.random()*7)+'s';p.appendChild(x)}
window.addEventListener('load',()=>setTimeout(()=>{document.getElementById('loader').style.opacity='0';document.getElementById('loader').style.visibility='hidden'},700));
